version: "3.9"
services:
  server:
    build: ./server
    ports:
      - "7000:7000"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/development.env
    depends_on:
      - db
    command: npm run dev
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
    env_file:
      - ./client/.env
    command: npm start  
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pern_clothing_store_pos
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=root  
    depends_on:
      - client        
volumes:
  pg_data:
  