import inventoryPageLocalization from './InventoryPageLocalization.json';
import storePageLocalization from './StorePageLocalization.json';
import indexStoreInventoryPageLocalization from './IndexStoreInventoryPageLocalization.json';
import createStoreInventoryPageLocalization from './CreateStoreInventoryPageLocalization.json';
import indexStoreTransactionPageLocalization from './IndexStoreTransactionPageLocalization.json';
import createStoreTransactionPageLocalization from './CreateStoreTransactionPageLocalization.json';
import navigationsLocalization from './NavigationsLocalization.json';
import profilePageLocalization from './ProfilePageLocalization.json';
import indexInventoryTransferPageLocalization from './IndexInventoryTransferPageLocalization.json';
import createInventoryTransferPageLocalization from './CreateInventoryTransferPageLocalization.json';

export const InventoryPageLocalization = inventoryPageLocalization
export const StorePageLocalization = storePageLocalization
export const IndexStoreInventoryPageLocalization = indexStoreInventoryPageLocalization
export const CreateStoreInventoryPageLocalization = createStoreInventoryPageLocalization
export const IndexStoreTransactionPageLocalization = indexStoreTransactionPageLocalization
export const CreateStoreTransactionPageLocalization = createStoreTransactionPageLocalization
export const NavigationsLocalization = navigationsLocalization
export const ProfilePageLocalization = profilePageLocalization
export const IndexInventoryTransferPageLocalization = indexInventoryTransferPageLocalization
export const CreateInventoryTransferPageLocalization = createInventoryTransferPageLocalization

