import inventoryPageLocalization from './InventoryPageLocalization.json';
import storePageLocalization from './StorePageLocalization.json';
import indexStoreInventoryPageLocalization from './IndexStoreInventoryPageLocalization.json';
import createStoreInventoryPageLocalization from './CreateStoreInventoryPageLocalization.json';
import indexStoreTransactionPageLocalization from './IndexStoreTransactionPageLocalization.json';

export const InventoryPageLocalization = inventoryPageLocalization
export const StorePageLocalization = storePageLocalization
export const IndexStoreInventoryPageLocalization = indexStoreInventoryPageLocalization
export const CreateStoreInventoryPageLocalization = createStoreInventoryPageLocalization
export const IndexStoreTransactionPageLocalization = indexStoreTransactionPageLocalization

